### ISSUE TITLE
教程页文字色值调整

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#104]
@Oaciqihz @panyinglei 

内容页所有绿色字体调整为：8F5A35

![image](https://github.com/decert-me/website/assets/42662626/5bd4f940-697a-44c1-bd44-0346832a0f19)
![image](https://github.com/decert-me/website/assets/42662626/1084e90a-4730-436a-93c2-177b67672cca)

调整后：
![image](https://github.com/decert-me/website/assets/42662626/37aa696b-7049-4720-8ab1-24fd3763f874)

**Comment by Oaciqihz** [comment]
@ccxdcyl 还需要夜晚模式的色值
