### ISSUE TITLE
添加编程挑战题

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#115]
发布挑战时支持编程挑战题，可以实时运行代码

Tasks：
- [x] 在线运行 solidity 代码 @liangjies
- [x] 设计页面和交互 @ccxdcyl
- [x] 文案 @ccxdcyl 
- [x] 整合进当前发布模块 @Oaciqihz
- [x] 测试相关功能 @panyinglei

**Comment by ccxdcyl** [comment]
@Oaciqihz编程题流程设计已更新，[设计图地址](https://lanhuapp.com/web/#/item/project/stage?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2 )

**Comment by 0xdwong** [comment]
![Image](https://github.com/decert-me/website/assets/121151857/60fe25bc-838b-4e77-b4a0-c8226fe123ce)

这里是不是应该加个颜色，更加容易区分成功/失败 @ccxdcyl

**Comment by 0xdwong** [comment]
失败的话，还需要把错误信息打印出来

**Comment by 0xdwong** [comment]
![Image](https://github.com/decert-me/website/assets/121151857/9c987b9e-b45c-42f5-80b5-227912c7d4d4)

添加编程挑战题代码测试用例时，下拉框是不是应该加个默认显示框

**Comment by 0xdwong** [comment]
![Image](https://github.com/decert-me/website/assets/121151857/bc6eb6b6-93dd-434f-bac4-e474d98f77c4)

红色框那里应该也需要有例子 @ccxdcyl

**Comment by panyinglei** [comment]
![Image](https://github.com/decert-me/website/assets/58837426/43f773ef-b65c-41e0-8f0d-60245cad59c4)

在添加编程题时，用户点击下拉框后不进行其他操作只滑动滚轮，下拉框会一直悬浮在页面上（需要让用户滑动时下拉框消失）

**Comment by 0xdwong** [comment]
如果同时存在「测试用例」和「代码测试」用例，代码测试用例用示例序号显示

**Comment by 0xdwong** [comment]
挑战界面，代码测试用例不可修改

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
代码模版、代码示例增加浮窗示例图。素材已更新蓝湖。


![Image](https://github.com/decert-me/website/assets/42662626/7b5a144a-f5ab-4384-8b28-1d4b5788ac68)



发布编程题浮窗效果参考蓝湖数值：
https://lanhuapp.com/web/#/item/project/detailDetach?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=1f25773c-d112-4475-98a3-870eb0798e52&fromEditor=true&type=image

**Comment by 0xdwong** [comment]
@ccxdcyl 移动端挑战界面“编程题”如何展示？

**Comment by Oaciqihz** [comment]
已完成
