### ISSUE TITLE
更换正式 UI

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#117]
替换当前的临时UI

Tasks：
- [x] 设计UI @ccxdcyl
- [x] 替换UI @Oaciqihz

**Comment by ccxdcyl** [comment]
@Oaciqihz DeCertUI蓝湖地址：https://lanhuapp.com/web/#/item/project/stage?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2

**Comment by 0xdwong** [comment]
@panyinglei @ccxdcyl 看下效果
