### ISSUE TITLE
编程题挑战页效果调整

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#123]
@Oaciqihz @panyinglei @0xdwong
编程题挑战页效果：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=8827ad7b-439a-4232-8814-e45a60478243&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image

**Comment by ccxdcyl** [comment]
@Oaciqihz @0xdwong @panyinglei 
补充了手机端效果：
@Oaciqihz 
有个提示滑动查看挑战题：
出现时机：仅第一次挑战编程题提示即可。
素材在蓝湖：https://lanhuapp.com/web/#/item/project/detailDetach?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=97c1c402-460a-4802-bb80-7b2205c85606&fromEditor=true&type=image
效果参考附件

**Comment by Oaciqihz** [comment]
已完成
