### ISSUE TITLE
官网其它页面UI替换

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#126]
decert.me 其它页面UI替换
Tasks：
- [ ] 页面设计 @ccxdcyl 
- [ ] 根据设计开发 @Oaciqihz 
- [ ] 测试验收 @panyinglei

**Comment by 0xdwong** [comment]
@ccxdcyl 14号之前出一版设计，讨论下

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei @0xdwong 设计稿蓝湖地址：
https://lanhuapp.com/web/#/item/project/stage?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2

**Comment by panyinglei** [comment]
页面ui已经替换
