### ISSUE TITLE
添加技能SBT逻辑调整

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#133]
1.点击添加技能SBT，输入合约后，默认全部添加，可以选择隐藏哪些SBT。
2.确认后，在认证页面显示所有的SBT（公开和隐藏）。
3.合约下有新的SBT，打开认证页自动加载显示。（如果长时间停留页面，刷新后显示）

添加技能SBT交互：
鼠标滑入，出现公开icon（眼睛）。
点击眼睛，切换为隐藏，当SBT隐藏时，显示隐藏icon。 
鼠标滑入隐藏icon，提示隐藏。
 鼠标滑入公开icon，提示公开。

移动端添加技能SBT交互：
点击nft图片，出现公开icon（眼睛）。
点击眼睛，切换为隐藏，当SBT隐藏时，显示隐藏icon。 
长按隐藏icon，提示隐藏。
 长按公开icon，提示公开。

**Comment by panyinglei** [comment]
相关ui、功能已经实现
