### ISSUE TITLE
添加“修改挑战”功能

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#138]
需求：
挑战对应SBT未有mint时才可以更改，有mint后不可以更改

**Comment by 0xdwong** [comment]
需求：
1. 挑战对应SBT未有mint时才可以更改，有mint后不可以更改

**Comment by ccxdcyl** [comment]
1.鼠标滑入挑战内容框，出现【编辑按钮】。
点击【编辑按钮】打开挑战题目编辑页。
2.当已有挑战者领取NFT，不可修改，此时【编辑按钮】为灰色，点击弹出message：
中文：抱歉，已有挑战者领取SBT，内容不可更改。
英文：Sorry, Challenger claimed SBT，cannot modify content.

![Image](https://github.com/decert-me/website/assets/42662626/593f14ee-fce7-4ac1-98dc-259c80e5f9ae)


web设计图效果：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=b8a59aee-0e6f-47d1-91a2-f86ff8fa86dd&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image
移动端：

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
如果发布者修改了挑战内容：
1.当挑战者已答题过，但是没有【领取】SBT，进入【挑战】时，提示：【发布者】修改了挑战内容，请重新挑战。
确认后清空之前的答题记录。

2.当挑战者正在答题，提交后，分数不通过，重新答题，进入【挑战】时，提示：【发布者】修改了挑战内容，请重新挑战。
确认后清空之前的答题记录。

3.当挑战者正在答题，提交后，分数通过。在mint时，提示：【发布者】修改了挑战内容，请重新挑战。
确认后清空之前的答题记录。

4.未答题时，进入【挑战】时，刷新显示修改的挑战内容。

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 挑战修改后，弹窗提示逻辑以及文案

**Comment by panyinglei** [comment]
1.预览界面的按钮位置偏移
2.修改挑战页面：
    【发布挑战】改为【保存】/save
    【确认发布】改为【保存】/save
    发布挑战页面的按钮文字不用修改


![Image](https://github.com/decert-me/website/assets/58837426/3dc65c24-a843-4c4f-922f-feaf1dda5d4d)


![Image](https://github.com/decert-me/website/assets/58837426/442f10e6-1053-4ab4-83b7-d910a1f4afb4)

@Oaciqihz

**Comment by ccxdcyl** [comment]
@panyinglei @Oaciqihz 
中文：编辑挑战
英文：Edit Challenge



![Image](https://github.com/decert-me/website/assets/42662626/40738c48-108d-4a7a-8c7e-a264f1371ae1)
