### ISSUE TITLE
认证页面加一个手动刷新按钮

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#140]

**Comment by ccxdcyl** [comment]
蓝湖web效果：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=46e37370-a52a-4814-9d4e-00b12fa16069&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image
蓝湖移动端效果：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=9297cf23-5c01-4916-827c-3d316cc22d1e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image

**Comment by panyinglei** [comment]
相关ui功能均已经实现
