### ISSUE TITLE
新版UI中存在的问题

### ISSUE THREAD

**Issue by panyinglei** [decert-me/website#141]
1.首页标语的下划线样式与蓝湖不一致
![image](https://github.com/decert-me/website/assets/58837426/3ee8b637-3318-4fff-bf1c-4b23189c1bee)

https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=58518d3f-7f0e-45ae-8969-41853bc70a47&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image

英文字体需要加粗，可参考【认证】页英文

**Comment by panyinglei** [comment]
移动端添加SBT的勾选框去掉，一排显示的sbt个数有误（需要显示3个）
![image](https://github.com/decert-me/website/assets/58837426/424d39d0-d23a-4fbc-afdf-e38249daaed3)

**Comment by panyinglei** [comment]
开始挑战的字体大小显示有误设计图上需要14px(0.875rem)
![image-20230626094311198](https://github.com/decert-me/website/assets/58837426/40a45d8f-6b4b-489c-aca1-a17c2628f73e)

**Comment by panyinglei** [comment]
认证页面的文案更改your web3 Vitae & reputation portal----》View the NFT that has achieved the relevant competency certification

![image-20230626092822575](https://github.com/decert-me/website/assets/58837426/8390022a-098a-4860-98a6-b1060492355e)

**Comment by panyinglei** [comment]
5.认证详情页面中的文案与素材的修改
![image](https://github.com/decert-me/website/assets/58837426/f059aa52-b566-40ee-9a70-f2b91156757d)

**Comment by panyinglei** [comment]
sbt点击眼睛图标隐藏后，被隐藏的sbt没有在隐藏子页面显示
![image](https://github.com/decert-me/website/assets/58837426/570b3a30-d86b-4fea-9279-2f21aa4da59a)

**Comment by panyinglei** [comment]
答题页面中的答题按钮没有与边框对齐

![image](https://github.com/decert-me/website/assets/58837426/9e0ff225-a5e3-483b-8b3a-cf89fd6680e5)

蓝湖：https://lanhuapp.com/link/#/invite?sid=XScDh47

**Comment by panyinglei** [comment]
挑战页面的图片圆角与难度等级的星星素材需要用描边（现在的为投影）

![image](https://github.com/decert-me/website/assets/58837426/cd545748-f43a-4941-848c-1d4e4eba6171)

页面设计图：https://lanhuapp.com/link/#/invite?sid=XKhuF3a
蓝湖素材:https://lanhuapp.com/link/#/invite?sid=Xy2qBpa

**Comment by 0xdwong** [comment]
> 1.首页标语的下划线样式与蓝湖不一致 ![image](https://user-images.githubusercontent.com/58837426/248717435-3ee8b637-3318-4fff-bf1c-4b23189c1bee.png)
> 
> https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=58518d3f-7f0e-45ae-8969-41853bc70a47&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image

测试评论

**Comment by ccxdcyl** [comment]
> 1.首页标语的下划线样式与蓝湖不一致 ![image](https://user-images.githubusercontent.com/58837426/248717435-3ee8b637-3318-4fff-bf1c-4b23189c1bee.png)
> 
> https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=58518d3f-7f0e-45ae-8969-41853bc70a47&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image

字体需要加粗

**Comment by ccxdcyl** [comment]
9.认证页面，
中文标题：查查“码”过什么
英文标题：What have you build.

中文副标题：Web3 履历与信誉记录
英文副标题：web3 Vitae & reputation portal
![image](https://github.com/decert-me/website/assets/42662626/7714b5b4-4a02-4e22-bb09-98ed322b1207)
认证

**Comment by panyinglei** [comment]
现在剩余1、5还没有修改完

**Comment by panyinglei** [comment]
之前版本创建的挑战难度与挑战时间显示有问题
![image](https://github.com/decert-me/website/assets/58837426/2a7fd00c-e284-4c57-87d6-d1e4d3e9f043)
![image](https://github.com/decert-me/website/assets/58837426/13db62d8-82a0-450d-ad6e-c9528bfb1e7b)

**Comment by panyinglei** [comment]
上述问题已经解决

**Comment by ccxdcyl** [comment]
@panyinglei @Oaciqihz 
新增了一个页码效果：
蓝湖地址：https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=e7570350-4982-43d7-8bc5-a49a0a03be72&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&fromEditor=true&type=image
![image](https://github.com/decert-me/website/assets/42662626/a63c6e5d-14d9-42fd-a4da-9cb38bce0044)

**Comment by panyinglei** [comment]
页码样式已经修改完成
