### ISSUE TITLE
教程里面添加挑战

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#150]

**Comment by ccxdcyl** [comment]
挑战入口 
- 固定在左下方，未学习教程可直接进行挑战。点击打开新窗口，在新窗口挑战。 
- 最后一个章节下面，增加挑战入口，点击在当前窗口跳转挑战页面。 
- 挑战链接在DeCert/tutorials/tutorials.json里增加


![Image](https://github.com/decert-me/website/assets/42662626/42710121-d5b7-4f9a-8642-9ec1187ba79b)




效果图：
https://lanhuapp.com/web/#/item/project/stage?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all
