### ISSUE TITLE
发布挑战时，预览需要支持显示答案

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#154]

**Comment by ccxdcyl** [comment]
@panyinglei @Oaciqihz 
1.默认题目后面增加显示分数
2.默认在正确答案后显示（正确答案）：参考蓝湖设计稿
3.预览模式导航栏隐藏，改为显示字段【预览模式】、【退出预览】
4.点击提交/执行测试用例需要提示。（见下方文案）
5.点击答题记录，出现弹窗，点击需要可以跳转查看题目

文案：
仅创建者可见
Only Creater is visible

当前为预览模式，不可提交。
Currently in preview mode, cannot be submitted.

当前为预览模式，不可执行测试用例。
Currently in preview mode, test cases cannot be executed.


蓝湖更新地址
https://lanhuapp.com/web/#/item/project/stage?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2

**Comment by Oaciqihz** [comment]
@ccxdcyl 
缺少文案: `正确答案`
