### ISSUE TITLE
推特授权绑定账号

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#172]
完成挑战后，引导用户绑定推特。用户发推后，直接读取用户的推文时间线，检查是否有发推。不用用户手动粘贴推文链接地址。

Tasks：
- [ ] 研究推特相关 API @liangjies
- [ ] 制定相关流程 @ccxdcyl
- [ ] 获取推文并验证 @liangjies
- [ ] 调整相关页面 @Oaciqihz

**Comment by ccxdcyl** [comment]
@Oaciqihz @Oaciqihz @panyinglei 
流程：
1.点击绑定twitter，弹出twitter绑定窗口【参考图1】
2.绑定后，返回挑战结果页
3.可点击核实是否已绑定。
4.点击分享twitter，跳转twitter页面进行分享。【参考图2】
5.点击分享twitter后，挑战结果页开始检查推文分享。（取消原输入推文链接）



![Image](https://github.com/decert-me/website/assets/42662626/d3bc59f1-c7d6-4829-ad7b-71361783ce8d)


正在验证...
Verifying...

检查到已经分享推文后提示：
- 分享成功
稍后系统将会把SBT空投至你的钱包账户，请勿删除此推文。
Sharing Success
The system will airdrop the SBT to your wallet later, please do not delete the tweet.

图1:

![Image](https://github.com/decert-me/website/assets/42662626/1254de2f-0bac-4af8-bb30-55959e9225ae)

图2:
![Image](https://github.com/decert-me/website/assets/42662626/8b4b7bb9-86a1-4d0f-862b-51b9c82781a3)
