### ISSUE TITLE
添加支持solana链

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#237]
前端支持solana钱包登录，支持空投NFT到solana钱包

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
1.钱包支持Solanan链的地址登录，
点击连接，选择Metamask/Solana Wallet/Walletconnect
当点击Solana Wallet，弹出支持Solana链的钱包列表

蓝湖-【支持solana登录】
https://lanhuapp.com/web/#/item/project/stage?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all

2.在认证页，增加Solana标识
蓝湖-【素材】：https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=22498692-3c29-42a8-b96f-3657c73aa3e0&fromEditor=true&type=image

**Comment by Oaciqihz** [comment]
3.cert页支持solana

**Comment by Oaciqihz** [comment]
4.claim改为点击claim

**Comment by 0xdwong** [comment]
5. discrod 支持绑定 Solana 钱包
