### ISSUE TITLE
合辑NFT功能

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#252]
1.合辑NFT创建规则：
后台创建合辑时，输入作者地址，创建后，对应地址链接钱包后，可在合辑简介页面，【创建NFT】
合辑信息、合辑包含挑战在后台操作。

2.在合辑未创建NFT时，用户鼠标滑入【领取】按钮，提示【等待合辑更新完后方可领取】
NFT创建后，点击【领取】，提示【请先完成挑战】

 

蓝湖地址-【合辑NFT】：https://lanhuapp.com/web/#/item/project/stage?tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2

**Comment by panyinglei** [comment]
补充相关的合辑功能，后台在合辑nft创建后就不允许对该合辑进行编辑，合辑中如果有未上架的挑战时合辑nft被创建，合辑中的挑战数量按照创建时合辑中上架的数量显示

**Comment by ccxdcyl** [comment]
补充：
在完成合辑内的挑战后，增加引导「合辑」简介页面。
点击领取，弹窗通知
https://lanhuapp.com/web/#/item/project/detailDetach?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&image_id=a72770f7-7fce-40c5-b361-7602156aa31d&fromEditor=true&type=image

**Comment by 0xdwong** [comment]
> 补充相关的合辑功能: 1.后台在合辑nft创建后就不允许对该合辑进行编辑 2.合辑中如果有未上架的挑战时合辑nft被创建，合辑中的挑战数量按照创建时合辑中上架的数量显示

之后再迭代
