### ISSUE TITLE
挑战支持开放式题目

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#271]
- [x] 需求整理
- [x] 原型设计
- [x] 开发

**Comment by ccxdcyl** [comment]
需求：
https://decert.notion.site/38ceb05abfa748158dd0d3aba17172c2?pvs=4

**Comment by ccxdcyl** [comment]
补充：
1.点击通知结果，新打开标签页查看。
2.通知文字格式：
「恭喜通过挑战」**或者**「很遗憾，挑战未通过」
你在「挑战标题」的答题成绩为XX分，「可领取一枚SBT！」**或者**「请继续加油吧」

我知道了
前往查看

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
挑战列表页面：

待评分
To be reviewed

蓝湖地址
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=973b3d61-ca58-4321-b16d-70bf9cdb033a&fromEditor=true&type=image

**Comment by ccxdcyl** [comment]
修改：开放题提交后等待页面

文案修改：
评分中
In review

挑战列表页面：
【待评分】改为【评分中】
英文：In review

蓝湖：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=8a7e1844-7416-4055-9968-6c1750d81c15&fromEditor=true&type=image

**Comment by ccxdcyl** [comment]
1.后台「挑战ID」改为「挑战编号」，点击可跳转对应的挑战链接
2.用户地址支持复制全部
3.列表分数去掉，在「开放题」内显示【本体分数】和【判定结果】分数，如图1
4.列表【编辑】改为评分
5.【开放题审核】改为【开放题评分】



![Image](https://github.com/decert-me/website/assets/42662626/dea1387e-616c-4625-8ec3-47bb767ac54a)



![Image](https://github.com/decert-me/website/assets/42662626/9f05dd55-561d-4958-89fc-7b761c7f280b)

**Comment by ccxdcyl** [comment]
个人中心增加「评分中」

蓝湖：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=bb1d1a55-2a2e-4c0b-8bb5-6e965c35ea81&fromEditor=true&type=image

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
补充逻辑：下架的挑战
1.下架的挑战，挑战者提交的记录在评分列表不显示
2.如果重新上架，之前的挑战者的记录也重新显示。
3.如果重新上架的挑战，内容做了更改，之前的挑战者提交记录不用显示。

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
修改文案：
挑战包含开放题，评分需要一段时间，请耐心等待...
The challenge consists of open quizzes, it will take some time to score, 
please be patient...



![Image](https://github.com/decert-me/website/assets/42662626/750e9de7-b761-4b97-88d0-b571683bb5c1)

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
补充：去掉显示题目类型
选择题、填空题、开放题都去掉

![Image](https://github.com/decert-me/website/assets/42662626/5f54d29c-b594-4566-bbb7-dc03df0018ea)

**Comment by panyinglei** [comment]
下一版需求链接：
https://github.com/orgs/decert-me/projects/2/views/1?pane=issue&itemId=46004512
