### ISSUE TITLE
挑战内容支持多语言

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#291]

**Comment by 0xdwong** [comment]
See disscussions: https://github.com/orgs/decert-me/discussions/280
见讨论: https://github.com/orgs/decert-me/discussions/280

**Comment by ccxdcyl** [comment]
@liangjies @Oaciqihz @panyinglei 

补充：
个人中心：
- 「Created」中显示自己发布的挑战内容（包括中文挑战、英文挑战），点击「修改」，如果是中文，在编辑处编辑中文，如果是英文编辑英文。
- 「Completed」中，显示已完成的所有挑战（网站中文就显示中文、英文就显示英文）。

NFT元数据
- 铸造时的元数据中attributes包含两种语言的IPFS链接
- 铸造时，name、Description和 challenge_title与挑战时的语言一致
