### ISSUE TITLE
优化代码挑战运行

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#304]
挑战页面：
- “执行结果”提示错误，“编译失败”，给的提示是”测试用例失败“
- 优化：执行测试用例需要清空之前的执行结果信息（有的话）
- 优化: “执行结果”返回的信息需需要支持换行
- 优化: 需要“还原到模板“的功能

发布挑战页面：
- 优化: “执行结果”返回的信息需需要支持换行

**Comment by panyinglei** [comment]
【发布页面】执行测试用例也需要清空之前执行结果信息

**Comment by 0xdwong** [comment]
> 【发布页面】执行测试用例也需要清空之前执行结果信息

@Oaciqihz
