### ISSUE TITLE
发布链下证书

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#328]
zCloak 
- 官网：https://zcloak.network/
- Github：https://github.com/zCloak-Network
- example：https://github.com/zCloak-Network/zkid-sdk-example

**Comment by 0xdwong** [comment]
![Image](https://github.com/decert-me/website/assets/121151857/cba4b609-2b79-46e4-838b-ebfd380f13e0)

**Comment by 0xdwong** [comment]
1. 绑定DID
    - 用户使用当前账号去绑定DID（平台帮用户生成，用户而非平台去保存助记词）。暂定一对一绑定（之后可以解绑，以防用户忘记DID账号助记词）
    - 绑定需要发起签名，签名信息包括当前账号地址和DID账号。后端保存签名。
    - 绑定时机？**（待定）**
    
2. 颁发证书
  - 通过挑战即可颁发证书（多次挑战以哪个为准？），或者需要用户去请求颁发证书 **（待定）**
  - 先生成证书，NFT之后再接入（等【多链支持】上线后）
 
3. 展示证书
  - 认证页面支持检索用户的证书，通过检索当前账号绑定的 DID账号
  - 证书展示参考 zCloak 的证书

**Comment by ccxdcyl** [comment]
补充：
个人中心
- 显示DID账号
- 支持复制DID账号
- 支持下载（导出）Keysfile
