### ISSUE TITLE
链下证书展示

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#339]
点击“证书”logo展示证书，样式参考zCloak（下图），去掉最下面那一栏，只保留“下载”和“分享到X”：

![Image](https://github.com/decert-me/website/assets/121151857/168e4478-f6fa-43e8-ac83-af3c572b3bf1)

**Comment by 0xdwong** [comment]
证书标题：DeCert.Me Challenge
证书描述：Congratulate on pass the challenge.
颁发者(Issuer)：did:zk:0x237Ec821FDF943776A8e27a9fd9dd6f78400071b

证书内容字段：
- Title (标题)
- ChallengeID (挑战ID)
- Pass （通过与否）
- Score （分数）
- Content （答题内容，ipfs）

**Comment by ccxdcyl** [comment]
效果图和模版见：
https://lanhuapp.com/web/#/item/project/stage?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all
