### ISSUE TITLE
发布挑战时提供 NFT 图片模板

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#342]
发布挑战时提供 NFT 模板供用户选择，用户也可以自行上传图片。

**Comment by 0xdwong** [comment]
- 用户如果自行上传图片，用户领到的NFT的图片即为该图片，eg：图1
- 用户如果选择模板，用户领到的NFT的图片为新生成的图片（模板+动态数据：标题、分数等），eg：图2

图1:



![Image](https://github.com/orgs/decert-me/projects/2/assets/121151857/775b909d-e3b8-4c82-a67d-9dfa87c187fe)



图2:


![Image](https://github.com/orgs/decert-me/projects/2/assets/121151857/65e4b126-a2e1-4a7e-8cd7-baf34f18cd5b)

**Comment by 0xdwong** [comment]
1. 图片上动态刻画什么内容？
- 标题
- 发布者？


2. 证书模板是不是要与NFT模板同步？

**Comment by ccxdcyl** [comment]
发布挑战时NFT图片处理方式：
- 提供默认模版图片供发布者选择
- 发布者可以自定义上传图片
- NFT图片显示规则：背景图（默认图片、自定义上传图片）+蒙版+文字（issuer）

证书显示规则
- 发布NFT时的「背景图」（默认图片、自定义上传图片）+蒙版+文字（issuer）
- 证书尺寸长方形
