### ISSUE TITLE
增加新的合作伙伴logo

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#383]

**Comment by ccxdcyl** [comment]
@Oaciqihz @panyinglei 
我们 Decert.me 合作伙伴列表， 可以把 zCloak、 GCC 、PlanckerDAO 、4Seas、 OpenBuild 、 https://web3camp.us/  加上
见蓝湖：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=7404ab36-8eed-4905-8080-0029b52b5905&fromEditor=true&type=image

**Comment by 0xdwong** [comment]
closed #385
