### ISSUE TITLE
开放题评分相关功能修改

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#398]
1.评分弹窗增加功能：
- 挑战者地址、增加批注

2.挑战者可以查看备注、答案评分结果

**Comment by ccxdcyl** [comment]
1.评分弹窗增加功能：

- 挑战者地址：（title为灰色，地址为黑色，且点击打开新标签页，在新标签页跳转地址个人主页）
- 批注：创建者在评分时可以对答案进行批注，批注编辑框支持滚动（参考效果）（挑战者需要查看到批注）
- 挑战总得分：默认不显示，评分后显示。（Tiele颜色为灰色，分数颜色为黑色）
- 挑战及格分（Title和分数都为灰色）
- 本题评分：默认不显示，评分后，显示分数
注：「挑战总得分」和「本题评分」需要跟随评分星星的变化，跟随变化对应的分数


![Image](https://github.com/decert-me/website/assets/42662626/8613a0b3-6801-43a9-9365-b08b54d57e38)




2.交互逻辑调整

- 提交成功后等待评分页 和 收到挑战结果的页面，有查看「挑战详情按钮」，点击跳转答题页（之前跳转的挑战详情页，改为答题页面）
- 当挑战包含开放题时，在得分处，显示通过/未通过；当挑战不包含开放题时，保持现在逻辑，显示分数。


![Image](https://github.com/decert-me/website/assets/42662626/871a8ebb-fec8-47d8-816b-35036bdfc02f)




3.挑战者查看开放题增加功能：
显示「查看批注」，点击弹窗显示「批注」内容，弹窗支持滚动查看，（参考效果）
增加「查看上次挑战」，点击显示「上次得分」和上次提交的答案



![Image](https://github.com/decert-me/website/assets/42662626/1ed9ff49-fac4-45b6-9716-d69eef32e4d9)

**Comment by 0xdwong** [comment]
显示【挑战者提交时间】已完成 #406
