### ISSUE TITLE
评分打分模块改为滑块

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/website#417]
当前为等级打分机制（0-5），改为滑块，可以细化分数

**Comment by ccxdcyl** [comment]
参考效果：https://ant.design/~demos/slider-demo-input-number

蓝湖地址：
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=47426818-6b4b-472a-8fc9-5f8f3c1a73b3&fromEditor=true&type=image

**Comment by ccxdcyl** [comment]
补充：
查看「上次得分」，从显示五角星，改为显示分数
