### ISSUE TITLE
挑战、教程页面筛选方案

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#421]
**教程页面与挑战页面改为一致的筛选方案。**

筛选需求：
1.通过搜索筛选：搜索可以根据输入标签、标题文字搜索出结果。

2.分类筛选：默认显示「All」，可以点击标签进行筛选。（单选）

3.页面UI效果见蓝湖-前端页面-挑战、教程增加筛选：图1
蓝湖地址：https://lanhuapp.com/web/#/item/project/stage?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all

图1

![Image](https://github.com/decert-me/website/assets/42662626/1fc022fe-a243-4151-96f4-ab0aa8b2c40d)

4.创建挑战页面，增加选择「分类」，一个挑战可以添加 5 个「分类」（分类的数量保持和分类标签一致）

5.后台：挑战列表-编辑-增加选择「分类」。（同上可添加最多5个分类，非必填项）（分类的数量保持和分类标签一致）
https://lanhuapp.com/web/#/item/project/detailDetach?pid=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all&project_id=0f031de8-1359-4c91-bb81-6fbe1c11aa8e&image_id=87d461e2-457b-40f4-8ea4-2a66acbfdbbe&fromEditor=true&type=image

6.没有选择分类，默认在「其它/Other」的分类里

**Comment by 0xdwong** [comment]
pr #423 #[143](https://github.com/decert-me/backend-go/pull/143)
