### ISSUE TITLE
增加获取地址数据信息的接口

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#422]
接口需要提供的信息有：
第一版接口：
- 地址完成挑战/获得NFT的数量

补充：NFT包括链上、链下证书（同一个挑战都拿了的话得去重）

**Comment by ccxdcyl** [comment]
（完善中）完整版接口：
2.地址完成挑战/获得NFT的时间
3.根据规则返回是否获得认证标签的资格。
- 例如规则设定为必须要获得8个NFT，最早获得的时间是1一个月上。

**Comment by 0xdwong** [comment]
接口：https://api.decert.me/v1/statistics/addressChallengeCount/<address>
返回数据中的 `claim_num` 字段表示“NFT”数量
