### ISSUE TITLE
后台：可查看批注和挑战者的答案

### ISSUE THREAD

**Issue by ccxdcyl** [decert-me/website#430]

**Comment by ccxdcyl** [comment]
「备注」更改为「评分详情」

点击「查看」，弹出弹窗 
弹窗显示内容： 
1.挑战标题
2.挑战者地址（可点击跳转个人主页）、昵称和标签（管理员可见）
3.提交时间
4.题目
5.答案：显示挑战者提交的答案
6.批注：显示批注的内容
7.附件
8.挑战总得分
9.挑战及格分
10:本地评分：（只显示分数即可）
11.上一题/下一题

效果图参考：


![Image](https://github.com/decert-me/website/assets/42662626/b903c5c8-e0c3-4737-961b-b65657cfbd0e)

**Comment by 0xdwong** [comment]
移到另一个[issue](https://github.com/decert-me/admin/issues/21)了
