### ISSUE TITLE
twitter 分享文案

### ISSUE THREAD

**Issue by xilibi2003** [decert-me/website#75]
中文：
很高兴完成了一个新的挑战 💪🏻。

我从 @decertme 获得一个 NFT 勋章。

你也可以参与挑战： https://decert.me/quests/xxx. 

En: 

Glad to have completed a new challenge 💪🏻

I  just claimed a free NFT medal from @decertme 

Meeting the Challenge and claim yours at  https://decert.me/quests/xxx.

**Comment by 0xdwong** [comment]
英文文案缺少句尾结束标点；徽章用 badge 更合适。
完整内容：
Glad to have completed a new challenge 💪🏻.

I just claimed a free NFT medal from @decertme .

Meeting the Challenge and claim yours at https://decert.me/quests/xxx.

**Comment by 0xdwong** [comment]
完整文案参考：
中文：
很高兴完成了一个新的挑战 💪🏻。

我从 @decertme 获得一个 NFT 勋章。

你也可以参与挑战： https://decert.me/quests/xxx

En:
Glad to have completed a new challenge 💪🏻.

I just claimed a free NFT badge from @decertme.

Meeting the challenge and claim yours at https://decert.me/quests/xxx
