### ISSUE TITLE
编辑个人资料的保存按钮不应该是灰色的

### ISSUE THREAD

**Issue by Nami-upchain** [decert-me/website#99]
![image](https://user-images.githubusercontent.com/68583807/236980060-28d05e25-1cd4-4be9-8122-4b132f4faf08.png
上图中，保存按钮是灰色的，让人误以为是有什么内容没有填写不能保存
建议让保存按钮亮起来

**Comment by ccxdcyl** [comment]
![image](https://user-images.githubusercontent.com/42662626/237053057-dcdcb20e-8070-41ce-8347-0905afd1bfbc.png)

改为：
默认「保存」按钮高亮，按钮颜色：222222
鼠标滑入，按钮颜色：000000

在没有编辑的情况下，点击保存，依然提示保存成功。

**Comment by 0xdwong** [comment]
@caoqizhi

**Comment by 0xdwong** [comment]
@panyinglei

**Comment by ccxdcyl** [comment]
@Oaciqihz 保存按钮效果不佳，颜色重新调整。
@panyinglei 
改为：
默认「保存」按钮高亮，按钮颜色：8F5A35
鼠标滑入，按钮颜色：9F7253
文字颜色ffffff不变

「取消」按钮颜色，白底：ffffff，描边333333，文字颜色333333
鼠标滑入。描边颜色：8F5A35，文字颜色：8F5A35

**Comment by 0xdwong** [comment]
@Oaciqihz
